### ISSUE TITLE
Refactor push function with updating status.csv

### ISSUE THREAD

**Issue by Mikanebu** [datahq/core-datasets-tools#10]
We want to push(publish) only valid core data packages. We can find all the statutes in `status.csv` file. 

## Acceptance criteria

* [x] When I run `push`. It pushes only valid packages and updates `status.csv`

## Tasks

* [x] refactor CoreTools.push method to check `status.csv` file for column `validated = true` and update after pushing column `published = true`
* [x] test

**Comment by anuveyatsu** [comment]
FIXED in #11
