### ISSUE TITLE
Move message column to right-hand most column

### ISSUE THREAD

**Issue by rufuspollock** [datahq/core-datasets-tools#12]
We want to have `validated_data_message` and `validated_metadata_message` columns to right-hand most column, so we can easily read status.csv on github 

## Acceptance criteria

* [x] columns `validated_data_message` and `validated_metadata_message` are moved to right-hand most column

## Tasks

* [x] move columns 'validated_data_message` and `validated_metadata_message` to right-hand most column

**Comment by Mikanebu** [comment]
FIXED
