### ISSUE TITLE
Have a URL to published data package

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/core-datasets-tools#15]
If I now go to `status.csv` and try to check published data package on the live site, I need to construct URL manullay by copy pasting base site URL + publisher `core` + package name. It would be much nicer if we had a URL the csv file.

Options:

* instead of having boolean in `published` field, we could have URL if published and dash (`-`) if not;
* we have `ok_on_datahub` field that could be used for that - have URL here (but maybe it should be used to indicate if everything is OK on the site, not just a URL)

## Acceptance criteria

* [x] I have datahub URL for published packages

## Tasks

TODO

**Comment by Mikanebu** [comment]
@anuveyatsu Probably, the first option is better, since we need column `ok_on_datahub` when everything is perfect on the site.

**Comment by Mikanebu** [comment]
FIXED
