### ISSUE TITLE
Set gravatar email for core user to datasets@okfn.org

### ISSUE THREAD

**Issue by rufuspollock** [datahq/core-datasets-tools#24]
This will give us the same gravatar as on: http://github.com/datasets

**Comment by anuveyatsu** [comment]
@rufuspollock This requires changes in assembler because we need to get email hash. At the moment, we're using userid as email hash to display Gravatars.

**Comment by rufuspollock** [comment]
@anuveyatsu hmmmmmmmmm. This is definitely starts to make me thing that merging in profile info needs to be done somewhere different from assembler (or we look profile info separately). For now the solution would be that the core user stops having core as its ownerid and gets its "real email" hash as owner id (but i don't like that because we might want to change emails).

Here's my suggested solution (this should really move to separate issues - as it does not relate to this particular item alone):

- Stop expecting ownerid to be the gravatar
  - => Stop showing user profile image in lists of results as we won't have that info (and looking up in user profile api is a PITA) => just have "by xxx" or use a generic icon - like we have now - i think latter is actually nicer (generic icon could be a square in some way!)
     - Note this is an example where inability to "join" in the DB is  a PITA (note if we started moving some user profile info to metastore we could probably do this join ...)
- On showcase page explicitly look up the user profile including avatar_url for that dataset owner from the profile api
  - => profile api should return avatar_url (which it can compute for now ...)
     - this provides some nice future proofing e.g. if we allow users to upload their profile images we can return the url to that rather than gravatar

All of this requires a bit of thought and probably a chat with @akariv 

As this is not urgent let's put this on hold.

**Comment by akariv** [comment]
I agree.

1. You should not assume that ownerid has any meaning - as it might change in the future to be something else.
2. The get_profile method we just added could indeed take care of this - return the avatar_url (if it exists), and in case it doesn't, calculate the gravatar url and return that to the user.

     * But I think an even better solution would be to create a separate API for that: get_profile_picture which would redirect to the correct image (and make sure it returns with caching headers with high values).

**Comment by rufuspollock** [comment]
Issue moved to [datahq/pm #27](https://github.com/datahq/pm/issues/27) via [**ZenHub**](https://www.zenhub.com/)
