### ISSUE TITLE
Change all recline style graphs with simple graphs 

### ISSUE THREAD

**Issue by rufuspollock** [datahq/core-datasets-tools#27]
See simple graph definition in: https://hackmd.io/JwEwjGDMCGBMsFoBsAWAHJBLhmggRgAzCbDDRkgCsAZgKaw35A==?both

Tasks

* [x] Check our render library supports simple views
  * Yes, it does support 
* [x] Identify all core datasets with recline views
  * Number of core data packages with recline view is 20
https://docs.google.com/spreadsheets/d/14kJluhePaMOx6vYBic0poVjDYK3I8-v_xF3sv4Focac/edit#gid=125116489
* [x] Replace recline views with simple views

**Comment by Mikanebu** [comment]
Number of core data packages with recline view is 20
https://docs.google.com/spreadsheets/d/14kJluhePaMOx6vYBic0poVjDYK3I8-v_xF3sv4Focac/edit#gid=125116489

**Comment by Mikanebu** [comment]
@rufuspollock With simple view:
https://testing.datahub.io/Mikanebu/natural-gas
```javascript=
"views": [
    {
      "name": "Graph",
      "title": "Graph",
      "specType": "simple",
      "spec": {
        "type": "lines",
        "group": "Date",
        "series": [
          "Price"
        ]
      }
    }
  ]
```
With recline view:
https://datahub.io/core/natural-gas
```javascript=
"views": [
    {
      "id": "Graph",
      "type": "Graph",
      "state": {
        "graphType": "lines",
        "group": "Date",
        "series": [
          "Price"
        ]
      }
    }
  ]
```

**Comment by Mikanebu** [comment]
@rufuspollock Could you take a look if it is ok, I will change the rest 19 core data packages

**Comment by rufuspollock** [comment]
@Mikanebu 

* you don't need the title property unless it differs from name. However i would recommend keeping it and it improving the title to something meaningful (not just graph!)
 * `name` should be lowercase and like other identifiers (e.g. lowercase, underscores etcx)
* It is `line` not `lines` for simple graph spec!

Based on these changes please go ahead.

**Comment by Mikanebu** [comment]
FIXED. See comments in description + committed to all 20 core datasets to use simple views.
Example: on site: http://datahub.io/core/natural-gas
repo: https://github.com/datasets/natural-gas-prices
Opened issue regarding bug in frontend:
https://github.com/datahq/frontend/issues/71

/spent 4.5h
