### ISSUE TITLE
Merge this with https://github.com/datasets/registry

### ISSUE THREAD

**Issue by rufuspollock** [datahq/core-datasets-tools#29]
Looking at this repo i think it probably makes sense to merge this with https://github.com/datasets/registry so that we have all the core datasets info and tooling in one place.

**Comment by Mikanebu** [comment]
FIXED, merged this repo into https://github.com/datasets/registry, `README.md` is moved into `registry` by adding new section `tooling`. Rest of the docs just copied

**Comment by zelima** [comment]
@Mikanebu I would rename that section to "Core Dataset Tools" and remove "Lint" part.  Also At the to of the README of this file say "Depreciated - moved link/where/moved"

**Comment by Mikanebu** [comment]
FIXED, added `Depreciated - moved https://github.com/datasets/registry` into `README.md` and removed lint and renamed section to `Core Dataset Tools` in registry
