### ISSUE TITLE
package.json update to have

### ISSUE THREAD

**Issue by Mikanebu** [datahq/core-datasets-tools#3]
## Acceptance criteria

* [ ] npm run should run call all: 
  * npm check
    * internally checkMetadata, checkData
  * npm clone
  * npm push

**Comment by Mikanebu** [comment]
FIXED

**Comment by zelima** [comment]
@Mikanebu Very strange naming for issue :)

**Comment by Mikanebu** [comment]
@zelima Any suggestions, please?

**Comment by zelima** [comment]
@Mikanebu well, it's closed already, but I would name it something like "run check, clone and push scripts with npm" and provide some good description
