### ISSUE TITLE
Refactor to use new validateMetadata & validateData functions from CLI

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/core-datasets-tools#6]
We implemented functions to validate metadata (against the latest schema) and resource against given schema in `datahub-cli` repo. Now we want to use these functions in `core-datasets-tools` repo so we do validation properly before pushing.

## Acceptance criteria

* [x] When I run `check` function I get report about data packages

## Tasks

* [x] refactor CoreTools.check method in `index.js`
* [x] test

**Comment by Mikanebu** [comment]
FIXED
